locals {
  tags = {
    Project     = var.project_name
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
  # We retrieve API keys and other secrets from AWS Secrets Manager
  manual_secrets_from_aws = jsondecode(
    data.aws_secretsmanager_secret_version.manual_secrets_version.secret_string
  )

  # Secrets generated by Terraform
  generated_secrets = {
  }

  # Merge secrets
  all_secrets = merge(
    local.manual_secrets_from_aws, 
    local.generated_secrets
  )
}